[build-system]  # блок для сборки и установки проекта по стандарту PEP 518
requires = ['poetry-core==2.2.1']  # зависимость для сборки проекта, не для работы приложения
build-backend = 'poetry.core.masonry.api'  # стандартный бекенд poetry

[tool.poetry]
package-mode = true  # нужна ли нам сборка пакета?
packages = [{ include = 'mypackage', from = 'src' }]  # mypackage - название папки, которую нужно собрать в пакет

[project]
name = 'ProjectName'
version = '1.0.0'
description = 'Короткое описание проекта'
authors = [
    { name = 'Name Surname', email = 'email@example.com' },
]
readme = 'README.md'

requires-python = '>=3.10,<=3.14'
dependencies = []
